quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/Quarkus-Lib

quarkus.smallrye-openapi.path=/books/swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/books/swagger-ui
quarkus.swagger-ui.filter=true
quarkus.dev-ui.enabled=false

smallrye.jwt.sign.key.location=privateKey_no_passphrase.pem
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key-format=PEM
smallrye.jwt.sign.key-algorithm=RS256